### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SpeedRider** [grondag/exotic-matter-2#2]
[crash-2020-08-14_03.56.14-client.txt](https://github.com/grondag/exotic-matter-2/files/5071173/crash-2020-08-14_03.56.14-client.txt)

crashed when crafting 
not enough crashes said your mod could be the cause and 2 others ill send them a crash report as well.

**Comment by grondag** [comment]
Exotic Matter/Exotic Blocks and other mods that rely on the Fabric rendering API currently aren't compatible with Sodium.  I believe Sodium plans to add support, but I do not have an ETA.  

For now, [Canvas](https://www.curseforge.com/minecraft/mc-mods/canvas-renderer) is an alternate renderer I produce that is faster than vanilla with visual improvements, but it is not as fast as Sodium.
